#Build Stage

FROM oven/bun:alpine AS builder

WORKDIR /app

COPY bun.lock package.json ./
RUN bun install --no-save --frozen-lockfile


COPY . .


RUN bun run build


# Runtime Stage

FROM oven/bun:alpine

WORKDIR /app


COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./
COPY --from=builder /app/bun.lock ./

RUN bun install --production --no-save --frozen-lockfile

EXPOSE 3000

CMD ["bun", "dist/index.js"]
